DELETE http://localhost:3003/api/blogs/62f67d843d910bae18714824 HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtldmljYWkiLCJpZCI6IjYyZjQxZTE2ZmQzMDM3ODgyOTY0MWY4NyIsImlhdCI6MTY2MDMyMDk2OSwiZXhwIjoxNjYwMzI0NTY5fQ.pSOLQRqNB2TzF8D0eHzComG9da5xV-Eo6cj_ys788Jc