POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtldmljYWkiLCJpZCI6IjYyZjQxZTE2ZmQzMDM3ODgyOTY0MWY4NyIsImlhdCI6MTY2MDMyMDk2OSwiZXhwIjoxNjYwMzI0NTY5fQ.pSOLQRqNB2TzF8D0eHzComG9da5xV-Eo6cj_ys788Jc

{
    "title": "test",
    "url": "www.abcdefg.com",   
    "likes": 6,
    "userId": "62f41e16fd30378829641f87"
}